services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ifhonese  # Senha do root
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pifhonese"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mobiauto_api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # Aguarda o MySQL estar pronto antes de iniciar o app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbmobiauto?useSSL=false&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ifhonese
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - minha_rede

volumes:
  mysql_data:

networks:
  minha_rede:
